### ISSUE TITLE
Add Animation Folder Exporter

### ISSUE THREAD

**Issue by raymondMataka** [Ploaj/StudioSB#14]
Can you add the ability to export a Folder of animations instead of one at a time? Thanks.

**Comment by Ploaj** [comment]
Okay, added a way to "batch convert"

In the embedded console in the gui use the command
`convanim "folder" "path to model as smd" format`
then press enter

the format is the extension you want to convert to i.e. .anim .smd .seanim etc

This does mean you have to export the model as smd first. I will add the ability to directly use the "nusktb" later
