### ISSUE TITLE
Why can't I export Models?

### ISSUE THREAD

**Issue by ninetalescommander** [Ploaj/StudioSB#18]
I already spoke about this on the Crossmod page but for whatever reason, it was closed before my issue was addressed.
I'm trying to export the models but it's not letting me.
Back in Crossmod, I would just right-click the nutdlb, save it as an SMD, and then work from there.
How do I do it here?

**Comment by ninetalescommander** [comment]
Edit: Ah I see, you have to name the file and type the file type, never mind.

**Comment by Demonslayerx8** [comment]
Open the model you want in StudioSB, then go to file>export, and then save it as a dae or smd

**Comment by ninetalescommander** [comment]
> Open the model you want in StudioSB, then go to file>export, and then save it as a dae or smd
> 
> edit: ofc he figures it seconds before I posted >_>

Yeah sorry, to be honest that happens to me a lot. I spend ages trying to figure it out, then I seek help, and then right after that I work it out lol
