### ISSUE TITLE
Melee Support

### ISSUE THREAD

**Issue by trstruth** [Ploaj/StudioSB#19]
I created an [issue](https://github.com/jam1garner/Smash-Forge/issues/351) in the Smash Forge repository but was informed by @ScanMountGoat that your development efforts have been moved to this project.

Was just curious what the current state of Melee support is in StudioSB and what the future plans are for it - I'm really interested in exporting the melee stage and character models/animations into a file format that unity can work with.  Are you aware of any other way to do this?  The support for opening and viewing melee models/animations in Smash Forge seemed nearly complete so I was hoping the issue was just due to some small bug - but doesn't seem like that's the case.

**Comment by Ploaj** [comment]
Currently StudioSB supports opening JOBJ "_joint" files from Melee as well as both animation formats used in melee (AnimJoint and Figatree).

You can simply open/export the playable character model files "Pl****.dat" as dae or smd. The animations are supported, but unlike forge you need to split them as they are all together in the Pl**AJ.dat files. 

I have a python 2.7 script for splitting them if you don't want to do it manually.
https://gist.github.com/Ploaj/c29e456ad7f2d853f07846cef7f6ea6d
```
Extracting Animations
AJSplit.py -x (Pl**.dat) (Pl**AJ.dat)
ex: AJSplit.py -x PlMr.dat PlMrAJ.dat
        Injecting Animations
AJSplit.py -i (Pl**.dat) (folder)
ex: AJSplit.py -i PlMr.dat PlMrAJ
```

For stage models you have to manually extract the model parts from the stage's dat file at the moment.

Using this tool (HSDRAW) you can open the dat. 
https://github.com/Ploaj/HSDLib/releases

The open the stage file (Gr**.dat)

Models
* Find "map_head".
* Under it you will see Model Groups.
** The first Model Group will not likely have a model
* Right click and export the root JOBJ nodes and save them with "_joint" at the end of the filename. 
** Ex: TestModel_joint.dat
* Open in StudioSB then export scene

Animation
* In the model group folder under the JOBJ node there may be a Joint Animation folder
* right click -> export on the AnimJoint with "_animjoint" at the end of the filename
* Open Model "_joint.dat" exported above with StudioSB
* Open the animation "__animjoint.dat" to view/export it

Hope that explanation is helpful. Melee support is still in development.

**Comment by trstruth** [comment]
@Ploaj Thanks for the detailed response, I'll definitely look into trying the stuff you've layed out here.

**Comment by trstruth** [comment]
@Ploaj alright I was able to make a huge amount of progress thanks to the info you typed out.

1. I am able to open the playable character models and extract them to .dae, which unity can then import.

2.  I was able to run the supplied python script and open the extracted files in StudioSB where they are working perfectly (!! so cool !!)

I'll look into the stage export process later, but for now I'm stuck on how I can export the animations from StudioSB in a way that unity can view them.  Any hints there?  I tried exporting the animation but wasn't sure which extension to use.  It defaulted to .dat and unity is not recognizing that.

**Comment by Ploaj** [comment]
.anim is probably the best format for preserving keyframes. I'm not entirely sure what animation formats unity supports directly other than fbx. 

You may have to use Maya to put the exported .anims into an fbx file, but I am unfamiliar with that workflow.
