### ISSUE TITLE
Character thrown and "special" grabbed and thrown(Snake, Incineroar) animations are broken

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [Ploaj/StudioSB#2]
![image](https://user-images.githubusercontent.com/33284629/52576391-e0135680-2e17-11e9-9f21-af965e3277ad.png)
Not sure what's up here but im guessing the "special" grabbed and thrown animations characters use while grabbed and thrown by either Snake or Incineroar use shared skeletons or something as they are in the snake and gaogen motion folders.
Character thrown animations in general are broken.

**Comment by Ploaj** [comment]
Those animations are coded to only use the rotations in-game so they can work for every character.

The format has to store translation too, so they store it as 0, 0, 0 which is why playing them as is looks like that.

**Comment by TabuuForteAkugun** [comment]
So technically they are NOT broken? 

I'm guessing they use the translation from the target fighter's T pose.
