### ISSUE TITLE
original c00 not showing up

### ISSUE THREAD

**Issue by roland3564** [Ploaj/StudioSB#3]
pls help me i have the latest open gl: when i import the original c00 folder nobody is showing up but there is the folder at the left of the viewport with grey names of the files
![helpmeh](https://user-images.githubusercontent.com/32875049/54041348-c91e1500-41c7-11e9-9d1f-83863cd7db5f.png)

**Comment by Demonslayerx8** [comment]
This tool isn't for smash WiiU, it's for Smash Ultimate.
