### ISSUE TITLE
Can't see model

### ISSUE THREAD

**Issue by Escope12** [Ploaj/StudioSB#37]
I can't see the model when I view it in StudioSB. Is it possible to fix it.
![Can't see model](https://user-images.githubusercontent.com/8963276/84549796-f3b62200-acd6-11ea-8839-b5125f1b0ec7.png)

**Comment by Jack-Hewn** [comment]
This is happening to me too. I had to borrow my friend's older version of the software to use it.

**Comment by ScanMountGoat** [comment]
Open a new issue if this is still happening on the latest version. There have been numerous rendering compatibility fixes.
