### ISSUE TITLE
UV Maps Missing

### ISSUE THREAD

**Issue by ninetalescommander** [Ploaj/StudioSB#39]
Ever since I downloaded the latest version and exported models as DAE, the UV Maps have just vanished. At first I thought it was because Min Min is new but it happens with all the characters.

**Comment by ScanMountGoat** [comment]
It's probably related the attribute naming issues. Try again on the latest and let me know if it works. Corrin's UVs seem to be exporting correctly now.

**Comment by ninetalescommander** [comment]
Perfect! Thank you.
