### ISSUE TITLE
Double saving of Tangent0 string and in wrong place in NUMSHB

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Ploaj/StudioSB#41]
When saving a NUMSHB on the latest StudioSB release, the `Tangent0` string is being written in the file twice instead of once and written in place of where the first `map1` string should be located. In the provided image, the top is what's occurring and the bottom is what's ideal (the string crossed out in blue is a mesh name).

![tangent0](https://user-images.githubusercontent.com/47584884/86523154-04ad0b80-be1d-11ea-9ee4-b57d00d18488.png)

**Comment by ScanMountGoat** [comment]
I found a subtle bug introduced in the exporting code for SSBHLib. I'll post a fix soon.
