### ISSUE TITLE
.nuanmb export with low compression breaks ingame 

### ISSUE THREAD

**Issue by WannaBeDev64** [Ploaj/StudioSB#49]
After updating to the newest build, I tried to export an animation over Sonic's Fair. When I tested it in-game, via ARCropolis, the animation spazzed out. Opening the exported file shows no problems. I tested compression levels 0.001, 0.01, and 0.05 and they all resulted in the same thing.

**Comment by ThatNintendoNerd** [comment]
Tested and working commit: https://github.com/Ploaj/StudioSB/tree/66d585abca372a690de3753a8206b67153b4ae69

**Comment by Temporalin** [comment]
From what I'm testing, commit 82182c3d617495cacd2dd0f1b6cc2a33d012be6 is the last `master` commit that works.

That commit is parent of a branch that updates SSBHLib. In commit a53a4af56cffb62e8a0e3ffaadc2ca24ad13ecca it is already broken.

This makes me think that the problem relies in the big SSBHLib update

**Comment by ScanMountGoat** [comment]
Ploaj comitted a compression fix that updated SSBHLib in 8c3a9bc11f500ac09b1eaa238f6d5808c67667e0 with the uncommitted changes you noticed @Temporalin. I didn't edit the animation compression, but it would have been replaced by my other changes due to not being committed. Thanks for the effort in helping to track this down.

**Comment by ScanMountGoat** [comment]
A gist containing both files. 
https://gist.github.com/ScanMountGoat/5296971328aeec63faa29cdf1f90e346

**Comment by Temporalin** [comment]
Happy to see you've figured it out! I was going to start looking into this again after my holidays. Is it fixed then?

**Comment by ScanMountGoat** [comment]
Not yet but it should be fixed in the next few days. Once I've updated SSBHLib and StudioSB, I'll test with people to make sure it resolves the issue.

**Comment by Temporalin** [comment]
Perfect! Thanks for your work!

**Comment by ScanMountGoat** [comment]
Should be fixed on the latest commit. Open a separate issue if there are any more issues with animation exporting.
