### ISSUE TITLE
StudioSB Anim Exporting problem.

### ISSUE THREAD

**Issue by Escope12** [Ploaj/StudioSB#5]
Everytime I export an animation from Smash Ultimate with StudioSB and I import it into BrawlBox, this happens.
![BrawlCrate_2019-04-27_13-16-16](https://user-images.githubusercontent.com/8963276/56852919-1593f000-68ef-11e9-9e0a-405b80daed02.png)

**Comment by Ploaj** [comment]
Are you exporting with radians or degrees?
BrawlBox only supports degrees iirc

**Comment by Escope12** [comment]
I don't know. How would I export it to degrees?

**Comment by Ploaj** [comment]
Should be an option when exporting.
Try updating if it doesn't show.

**Comment by Escope12** [comment]
Is there an option where you can make the animation not keyframe every frame because everytime I import anim files into BrawlBox, it keyframes every frame and it could cause filesize issue.

**Comment by Ploaj** [comment]
No, that's unfortunately how the animations are in Ultimate (and Smash 4 too).

There may be a way to "re-key" them with animation software, but I am sure. It's not going to be do-able from StudioSB though
