### ISSUE TITLE
Animation export issues

### ISSUE THREAD

**Issue by schiggysmallz** [Ploaj/StudioSB#52]
with the latest build exporting a custom animation totaly freaks out in game. In older builds (https://github.com/Ploaj/StudioSB/tree/66d585abca372a690de3753a8206b67153b4ae69) it kinda works but at the end of the animation when it transitions into another animation the last few frames freak out. Is there a way to fix it to make custom animations work correctly?

**Comment by ScanMountGoat** [comment]
The compression is broken. See #49. Apparently, there's also an issue with the frame count being off. This may be causing the weird behavior at the end of animations.

**Comment by ScanMountGoat** [comment]
This should be fixed on the latest version. The frame count and compression have been adjusted. If you're still having issues, reopen the issue or make a new issue.

**Comment by ScanMountGoat** [comment]
Edit: apparently this is still broken.

**Comment by ScanMountGoat** [comment]
should be fixed now. If you're still having issues. Make a new issue
