### ISSUE TITLE
Exported .nuanmb animations missing last frame

### ISSUE THREAD

**Issue by ssbucarlos** [Ploaj/StudioSB#55]
The animation.FrameCount variable in the ExportSBAnimation() function in IO_NUANMB.cs is one too low. As a result exported .nuanmb animations are missing the last frame. For debugging, I changed the '<' to '<=' and was able to export an animation without the issue. However the real solution lies in finding why framecount is off by one. Might be related, but in the .nuanmb parser in ssbhlib the 'framecount' value that gets parsed is already one too low, im thinking that that value encoded in .nuanmb files might not really be the framecount but rather the max frame index.

Tested by importing a dumped .nuanmb and re-exporting it back into game.

**Comment by ScanMountGoat** [comment]
https://github.com/Ploaj/StudioSB/blob/d00227ab61094d3f69d09c72c58d024e811db7cb/StudioSB/IO/Formats/IO_NUANMB.cs#L180-L255
