### ISSUE TITLE
Deleting and reordering object list in the program?

### ISSUE THREAD

**Issue by BookerEnd** [Ploaj/StudioSB#7]
Possible in the future to implement this? Just a quality of life change, saves having to re-import and export constantly.

**Comment by Ploaj** [comment]
Does the order matter in this game?

**Comment by Demonslayerx8** [comment]
Mesh order doesn't matter in this game at all, but does seem to affect kirby mods from when I was helping with feet kirby.

**Comment by zrksyd** [comment]
@Ploaj I'm making a mod where it would be easier if mesh order can be changed so the NUMDLB doesn't have to be modded and potentially cause issues.
