### ISSUE TITLE
how to assign a material

### ISSUE THREAD

**Issue by TheCrossovers** [Ploaj/StudioSB#77]
i don't know how to assign a material, Please tell me

**Comment by ScanMountGoat** [comment]
Cross Mod doesn't have this functionality at the moment. You can assign materials by editing a JSON (text file) with ssbh_lib_json or assign the materials in [StudioSB](https://github.com/Ploaj/StudioSB/releases). I'd recommend asking for help in the modding discord if you're still feeling stuck https://discord.gg/ASJyTrZ
